<?php
/**
 * SavedQueriesApi
 * PHP version 5
 *
 * @category Class
 * @package  sematext\stcloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace sematext\stcloud\API;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use sematext\stcloud\ApiException;
use sematext\stcloud\Configuration;
use sematext\stcloud\HeaderSelector;
use sematext\stcloud\ObjectSerializer;

/**
 * SavedQueriesApi Class Doc Comment
 *
 * @category Class
 * @package  sematext\stcloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SavedQueriesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteSavedQueryUsingDELETE
     *
     * Delete saved query
     *
     * @param  int $updateable_query_id updateableQueryId (required)
     *
     * @throws \sematext\stcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \sematext\stcloud\Model\GenericApiResponse
     */
    public function deleteSavedQueryUsingDELETE($updateable_query_id)
    {
        list($response) = $this->deleteSavedQueryUsingDELETEWithHttpInfo($updateable_query_id);
        return $response;
    }

    /**
     * Operation deleteSavedQueryUsingDELETEWithHttpInfo
     *
     * Delete saved query
     *
     * @param  int $updateable_query_id updateableQueryId (required)
     *
     * @throws \sematext\stcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \sematext\stcloud\Model\GenericApiResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteSavedQueryUsingDELETEWithHttpInfo($updateable_query_id)
    {
        $returnType = '\sematext\stcloud\Model\GenericApiResponse';
        $request = $this->deleteSavedQueryUsingDELETERequest($updateable_query_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\sematext\stcloud\Model\GenericApiResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteSavedQueryUsingDELETEAsync
     *
     * Delete saved query
     *
     * @param  int $updateable_query_id updateableQueryId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSavedQueryUsingDELETEAsync($updateable_query_id)
    {
        return $this->deleteSavedQueryUsingDELETEAsyncWithHttpInfo($updateable_query_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteSavedQueryUsingDELETEAsyncWithHttpInfo
     *
     * Delete saved query
     *
     * @param  int $updateable_query_id updateableQueryId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSavedQueryUsingDELETEAsyncWithHttpInfo($updateable_query_id)
    {
        $returnType = '\sematext\stcloud\Model\GenericApiResponse';
        $request = $this->deleteSavedQueryUsingDELETERequest($updateable_query_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteSavedQueryUsingDELETE'
     *
     * @param  int $updateable_query_id updateableQueryId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteSavedQueryUsingDELETERequest($updateable_query_id)
    {
        // verify the required parameter 'updateable_query_id' is set
        if ($updateable_query_id === null || (is_array($updateable_query_id) && count($updateable_query_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $updateable_query_id when calling deleteSavedQueryUsingDELETE'
            );
        }

        $resourcePath = '/users-web/api/v3/savedQueries/{updateableQueryId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($updateable_query_id !== null) {
            $resourcePath = str_replace(
                '{' . 'updateableQueryId' . '}',
                ObjectSerializer::toPathValue($updateable_query_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSavedQueriesForAppUsingGET
     *
     * Get saved queries for an app
     *
     * @param  int $app_id appId (required)
     *
     * @throws \sematext\stcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \sematext\stcloud\Model\GenericApiResponse
     */
    public function getSavedQueriesForAppUsingGET($app_id)
    {
        list($response) = $this->getSavedQueriesForAppUsingGETWithHttpInfo($app_id);
        return $response;
    }

    /**
     * Operation getSavedQueriesForAppUsingGETWithHttpInfo
     *
     * Get saved queries for an app
     *
     * @param  int $app_id appId (required)
     *
     * @throws \sematext\stcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \sematext\stcloud\Model\GenericApiResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSavedQueriesForAppUsingGETWithHttpInfo($app_id)
    {
        $returnType = '\sematext\stcloud\Model\GenericApiResponse';
        $request = $this->getSavedQueriesForAppUsingGETRequest($app_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\sematext\stcloud\Model\GenericApiResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSavedQueriesForAppUsingGETAsync
     *
     * Get saved queries for an app
     *
     * @param  int $app_id appId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSavedQueriesForAppUsingGETAsync($app_id)
    {
        return $this->getSavedQueriesForAppUsingGETAsyncWithHttpInfo($app_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSavedQueriesForAppUsingGETAsyncWithHttpInfo
     *
     * Get saved queries for an app
     *
     * @param  int $app_id appId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSavedQueriesForAppUsingGETAsyncWithHttpInfo($app_id)
    {
        $returnType = '\sematext\stcloud\Model\GenericApiResponse';
        $request = $this->getSavedQueriesForAppUsingGETRequest($app_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSavedQueriesForAppUsingGET'
     *
     * @param  int $app_id appId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSavedQueriesForAppUsingGETRequest($app_id)
    {
        // verify the required parameter 'app_id' is set
        if ($app_id === null || (is_array($app_id) && count($app_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_id when calling getSavedQueriesForAppUsingGET'
            );
        }

        $resourcePath = '/users-web/api/v3/apps/{appId}/savedQueries';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($app_id !== null) {
            $resourcePath = str_replace(
                '{' . 'appId' . '}',
                ObjectSerializer::toPathValue($app_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation saveQueryUsingPOST
     *
     * Create saved query
     *
     * @param  \sematext\stcloud\Model\SavedQuery $saved_query_dto savedQueryDto (required)
     *
     * @throws \sematext\stcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \sematext\stcloud\Model\GenericApiResponse
     */
    public function saveQueryUsingPOST($saved_query_dto)
    {
        list($response) = $this->saveQueryUsingPOSTWithHttpInfo($saved_query_dto);
        return $response;
    }

    /**
     * Operation saveQueryUsingPOSTWithHttpInfo
     *
     * Create saved query
     *
     * @param  \sematext\stcloud\Model\SavedQuery $saved_query_dto savedQueryDto (required)
     *
     * @throws \sematext\stcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \sematext\stcloud\Model\GenericApiResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function saveQueryUsingPOSTWithHttpInfo($saved_query_dto)
    {
        $returnType = '\sematext\stcloud\Model\GenericApiResponse';
        $request = $this->saveQueryUsingPOSTRequest($saved_query_dto);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\sematext\stcloud\Model\GenericApiResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation saveQueryUsingPOSTAsync
     *
     * Create saved query
     *
     * @param  \sematext\stcloud\Model\SavedQuery $saved_query_dto savedQueryDto (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function saveQueryUsingPOSTAsync($saved_query_dto)
    {
        return $this->saveQueryUsingPOSTAsyncWithHttpInfo($saved_query_dto)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation saveQueryUsingPOSTAsyncWithHttpInfo
     *
     * Create saved query
     *
     * @param  \sematext\stcloud\Model\SavedQuery $saved_query_dto savedQueryDto (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function saveQueryUsingPOSTAsyncWithHttpInfo($saved_query_dto)
    {
        $returnType = '\sematext\stcloud\Model\GenericApiResponse';
        $request = $this->saveQueryUsingPOSTRequest($saved_query_dto);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'saveQueryUsingPOST'
     *
     * @param  \sematext\stcloud\Model\SavedQuery $saved_query_dto savedQueryDto (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function saveQueryUsingPOSTRequest($saved_query_dto)
    {
        // verify the required parameter 'saved_query_dto' is set
        if ($saved_query_dto === null || (is_array($saved_query_dto) && count($saved_query_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $saved_query_dto when calling saveQueryUsingPOST'
            );
        }

        $resourcePath = '/users-web/api/v3/savedQueries';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($saved_query_dto)) {
            $_tempBody = $saved_query_dto;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation saveQueryUsingPUT
     *
     * Update saved query
     *
     * @param  \sematext\stcloud\Model\SavedQuery $saved_query_dto savedQueryDto (required)
     * @param  int $updateable_query_id updateableQueryId (required)
     *
     * @throws \sematext\stcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \sematext\stcloud\Model\GenericApiResponse
     */
    public function saveQueryUsingPUT($saved_query_dto, $updateable_query_id)
    {
        list($response) = $this->saveQueryUsingPUTWithHttpInfo($saved_query_dto, $updateable_query_id);
        return $response;
    }

    /**
     * Operation saveQueryUsingPUTWithHttpInfo
     *
     * Update saved query
     *
     * @param  \sematext\stcloud\Model\SavedQuery $saved_query_dto savedQueryDto (required)
     * @param  int $updateable_query_id updateableQueryId (required)
     *
     * @throws \sematext\stcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \sematext\stcloud\Model\GenericApiResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function saveQueryUsingPUTWithHttpInfo($saved_query_dto, $updateable_query_id)
    {
        $returnType = '\sematext\stcloud\Model\GenericApiResponse';
        $request = $this->saveQueryUsingPUTRequest($saved_query_dto, $updateable_query_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\sematext\stcloud\Model\GenericApiResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation saveQueryUsingPUTAsync
     *
     * Update saved query
     *
     * @param  \sematext\stcloud\Model\SavedQuery $saved_query_dto savedQueryDto (required)
     * @param  int $updateable_query_id updateableQueryId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function saveQueryUsingPUTAsync($saved_query_dto, $updateable_query_id)
    {
        return $this->saveQueryUsingPUTAsyncWithHttpInfo($saved_query_dto, $updateable_query_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation saveQueryUsingPUTAsyncWithHttpInfo
     *
     * Update saved query
     *
     * @param  \sematext\stcloud\Model\SavedQuery $saved_query_dto savedQueryDto (required)
     * @param  int $updateable_query_id updateableQueryId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function saveQueryUsingPUTAsyncWithHttpInfo($saved_query_dto, $updateable_query_id)
    {
        $returnType = '\sematext\stcloud\Model\GenericApiResponse';
        $request = $this->saveQueryUsingPUTRequest($saved_query_dto, $updateable_query_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'saveQueryUsingPUT'
     *
     * @param  \sematext\stcloud\Model\SavedQuery $saved_query_dto savedQueryDto (required)
     * @param  int $updateable_query_id updateableQueryId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function saveQueryUsingPUTRequest($saved_query_dto, $updateable_query_id)
    {
        // verify the required parameter 'saved_query_dto' is set
        if ($saved_query_dto === null || (is_array($saved_query_dto) && count($saved_query_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $saved_query_dto when calling saveQueryUsingPUT'
            );
        }
        // verify the required parameter 'updateable_query_id' is set
        if ($updateable_query_id === null || (is_array($updateable_query_id) && count($updateable_query_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $updateable_query_id when calling saveQueryUsingPUT'
            );
        }

        $resourcePath = '/users-web/api/v3/savedQueries/{updateableQueryId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($updateable_query_id !== null) {
            $resourcePath = str_replace(
                '{' . 'updateableQueryId' . '}',
                ObjectSerializer::toPathValue($updateable_query_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($saved_query_dto)) {
            $_tempBody = $saved_query_dto;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
