<?php
/**
 * TagApiControllerApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * TagApiControllerApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TagApiControllerApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getTagNamesUsingGET
     *
     * Gets tag names for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function getTagNamesUsingGET($app_ids, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        list($response) = $this->getTagNamesUsingGETWithHttpInfo($app_ids, $from, $to, $metrics, $logs, $events, $rum);
        return $response;
    }

    /**
     * Operation getTagNamesUsingGETWithHttpInfo
     *
     * Gets tag names for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTagNamesUsingGETWithHttpInfo($app_ids, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        $returnType = 'object';
        $request = $this->getTagNamesUsingGETRequest($app_ids, $from, $to, $metrics, $logs, $events, $rum);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getTagNamesUsingGETAsync
     *
     * Gets tag names for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTagNamesUsingGETAsync($app_ids, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        return $this->getTagNamesUsingGETAsyncWithHttpInfo($app_ids, $from, $to, $metrics, $logs, $events, $rum)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTagNamesUsingGETAsyncWithHttpInfo
     *
     * Gets tag names for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTagNamesUsingGETAsyncWithHttpInfo($app_ids, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        $returnType = 'object';
        $request = $this->getTagNamesUsingGETRequest($app_ids, $from, $to, $metrics, $logs, $events, $rum);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTagNamesUsingGET'
     *
     * @param  string $app_ids appIds (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getTagNamesUsingGETRequest($app_ids, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        // verify the required parameter 'app_ids' is set
        if ($app_ids === null || (is_array($app_ids) && count($app_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_ids when calling getTagNamesUsingGET'
            );
        }

        $resourcePath = '/spm-reports/api/v3/apps/{appIds}/tagNames';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if ($metrics !== null) {
            $queryParams['metrics'] = ObjectSerializer::toQueryValue($metrics);
        }
        // query params
        if ($logs !== null) {
            $queryParams['logs'] = ObjectSerializer::toQueryValue($logs);
        }
        // query params
        if ($events !== null) {
            $queryParams['events'] = ObjectSerializer::toQueryValue($events);
        }
        // query params
        if ($rum !== null) {
            $queryParams['rum'] = ObjectSerializer::toQueryValue($rum);
        }

        // path params
        if ($app_ids !== null) {
            $resourcePath = str_replace(
                '{' . 'appIds' . '}',
                ObjectSerializer::toPathValue($app_ids),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUsingGET2
     *
     * Gets values for specified tags for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  string[] $tag tag (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function getUsingGET2($app_ids, $tag, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        list($response) = $this->getUsingGET2WithHttpInfo($app_ids, $tag, $from, $to, $metrics, $logs, $events, $rum);
        return $response;
    }

    /**
     * Operation getUsingGET2WithHttpInfo
     *
     * Gets values for specified tags for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  string[] $tag tag (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUsingGET2WithHttpInfo($app_ids, $tag, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        $returnType = 'object';
        $request = $this->getUsingGET2Request($app_ids, $tag, $from, $to, $metrics, $logs, $events, $rum);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUsingGET2Async
     *
     * Gets values for specified tags for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  string[] $tag tag (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUsingGET2Async($app_ids, $tag, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        return $this->getUsingGET2AsyncWithHttpInfo($app_ids, $tag, $from, $to, $metrics, $logs, $events, $rum)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUsingGET2AsyncWithHttpInfo
     *
     * Gets values for specified tags for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  string[] $tag tag (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUsingGET2AsyncWithHttpInfo($app_ids, $tag, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        $returnType = 'object';
        $request = $this->getUsingGET2Request($app_ids, $tag, $from, $to, $metrics, $logs, $events, $rum);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUsingGET2'
     *
     * @param  string $app_ids appIds (required)
     * @param  string[] $tag tag (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getUsingGET2Request($app_ids, $tag, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        // verify the required parameter 'app_ids' is set
        if ($app_ids === null || (is_array($app_ids) && count($app_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_ids when calling getUsingGET2'
            );
        }
        // verify the required parameter 'tag' is set
        if ($tag === null || (is_array($tag) && count($tag) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tag when calling getUsingGET2'
            );
        }

        $resourcePath = '/spm-reports/api/v3/apps/{appIds}/metrics/filters';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if (is_array($tag)) {
            $queryParams['tag'] = $tag;
        } else
        if ($tag !== null) {
            $queryParams['tag'] = ObjectSerializer::toQueryValue($tag);
        }
        // query params
        if ($metrics !== null) {
            $queryParams['metrics'] = ObjectSerializer::toQueryValue($metrics);
        }
        // query params
        if ($logs !== null) {
            $queryParams['logs'] = ObjectSerializer::toQueryValue($logs);
        }
        // query params
        if ($events !== null) {
            $queryParams['events'] = ObjectSerializer::toQueryValue($events);
        }
        // query params
        if ($rum !== null) {
            $queryParams['rum'] = ObjectSerializer::toQueryValue($rum);
        }

        // path params
        if ($app_ids !== null) {
            $resourcePath = str_replace(
                '{' . 'appIds' . '}',
                ObjectSerializer::toPathValue($app_ids),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUsingGET3
     *
     * Gets values for specified tags for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  string[] $tag tag (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function getUsingGET3($app_ids, $tag, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        list($response) = $this->getUsingGET3WithHttpInfo($app_ids, $tag, $from, $to, $metrics, $logs, $events, $rum);
        return $response;
    }

    /**
     * Operation getUsingGET3WithHttpInfo
     *
     * Gets values for specified tags for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  string[] $tag tag (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUsingGET3WithHttpInfo($app_ids, $tag, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        $returnType = 'object';
        $request = $this->getUsingGET3Request($app_ids, $tag, $from, $to, $metrics, $logs, $events, $rum);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUsingGET3Async
     *
     * Gets values for specified tags for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  string[] $tag tag (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUsingGET3Async($app_ids, $tag, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        return $this->getUsingGET3AsyncWithHttpInfo($app_ids, $tag, $from, $to, $metrics, $logs, $events, $rum)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUsingGET3AsyncWithHttpInfo
     *
     * Gets values for specified tags for the given application identifiers appearing in the given time frame.
     *
     * @param  string $app_ids appIds (required)
     * @param  string[] $tag tag (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUsingGET3AsyncWithHttpInfo($app_ids, $tag, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        $returnType = 'object';
        $request = $this->getUsingGET3Request($app_ids, $tag, $from, $to, $metrics, $logs, $events, $rum);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUsingGET3'
     *
     * @param  string $app_ids appIds (required)
     * @param  string[] $tag tag (required)
     * @param  int $from from (optional)
     * @param  int $to to (optional)
     * @param  bool $metrics metrics (optional, default to true)
     * @param  bool $logs logs (optional, default to true)
     * @param  bool $events events (optional, default to false)
     * @param  bool $rum rum (optional, default to true)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getUsingGET3Request($app_ids, $tag, $from = null, $to = null, $metrics = 'true', $logs = 'true', $events = 'false', $rum = 'true')
    {
        // verify the required parameter 'app_ids' is set
        if ($app_ids === null || (is_array($app_ids) && count($app_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_ids when calling getUsingGET3'
            );
        }
        // verify the required parameter 'tag' is set
        if ($tag === null || (is_array($tag) && count($tag) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tag when calling getUsingGET3'
            );
        }

        $resourcePath = '/spm-reports/api/v3/apps/{appIds}/tags';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if (is_array($tag)) {
            $queryParams['tag'] = $tag;
        } else
        if ($tag !== null) {
            $queryParams['tag'] = ObjectSerializer::toQueryValue($tag);
        }
        // query params
        if ($metrics !== null) {
            $queryParams['metrics'] = ObjectSerializer::toQueryValue($metrics);
        }
        // query params
        if ($logs !== null) {
            $queryParams['logs'] = ObjectSerializer::toQueryValue($logs);
        }
        // query params
        if ($events !== null) {
            $queryParams['events'] = ObjectSerializer::toQueryValue($events);
        }
        // query params
        if ($rum !== null) {
            $queryParams['rum'] = ObjectSerializer::toQueryValue($rum);
        }

        // path params
        if ($app_ids !== null) {
            $resourcePath = str_replace(
                '{' . 'appIds' . '}',
                ObjectSerializer::toPathValue($app_ids),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
