<?php
/**
 * AppTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  sematext\stcloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace sematext\stcloud;

/**
 * AppTest Class Doc Comment
 *
 * @category    Class
 * @description App
 * @package     sematext\stcloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AppTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "App"
     */
    public function testApp()
    {
    }

    /**
     * Test attribute "ajax_threshold"
     */
    public function testPropertyAjaxThreshold()
    {
    }

    /**
     * Test attribute "app_type"
     */
    public function testPropertyAppType()
    {
    }

    /**
     * Test attribute "app_type_id"
     */
    public function testPropertyAppTypeId()
    {
    }

    /**
     * Test attribute "creator_email"
     */
    public function testPropertyCreatorEmail()
    {
    }

    /**
     * Test attribute "credit_card_expiry"
     */
    public function testPropertyCreditCardExpiry()
    {
    }

    /**
     * Test attribute "credit_card_number"
     */
    public function testPropertyCreditCardNumber()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "display_status"
     */
    public function testPropertyDisplayStatus()
    {
    }

    /**
     * Test attribute "first_data_saved_date"
     */
    public function testPropertyFirstDataSavedDate()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "integration"
     */
    public function testPropertyIntegration()
    {
    }

    /**
     * Test attribute "last_data_received_date"
     */
    public function testPropertyLastDataReceivedDate()
    {
    }

    /**
     * Test attribute "last_data_saved_date"
     */
    public function testPropertyLastDataSavedDate()
    {
    }

    /**
     * Test attribute "logged_in_user_app_role"
     */
    public function testPropertyLoggedInUserAppRole()
    {
    }

    /**
     * Test attribute "monthly_invoice_account"
     */
    public function testPropertyMonthlyInvoiceAccount()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "owner_email"
     */
    public function testPropertyOwnerEmail()
    {
    }

    /**
     * Test attribute "owning_organization"
     */
    public function testPropertyOwningOrganization()
    {
    }

    /**
     * Test attribute "page_load_threshold"
     */
    public function testPropertyPageLoadThreshold()
    {
    }

    /**
     * Test attribute "payment_method_id"
     */
    public function testPropertyPaymentMethodId()
    {
    }

    /**
     * Test attribute "plan"
     */
    public function testPropertyPlan()
    {
    }

    /**
     * Test attribute "prepaid_account"
     */
    public function testPropertyPrepaidAccount()
    {
    }

    /**
     * Test attribute "read_token"
     */
    public function testPropertyReadToken()
    {
    }

    /**
     * Test attribute "read_write_token"
     */
    public function testPropertyReadWriteToken()
    {
    }

    /**
     * Test attribute "registration_date"
     */
    public function testPropertyRegistrationDate()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "tokens"
     */
    public function testPropertyTokens()
    {
    }

    /**
     * Test attribute "trial_end_date"
     */
    public function testPropertyTrialEndDate()
    {
    }

    /**
     * Test attribute "url_group_limit"
     */
    public function testPropertyUrlGroupLimit()
    {
    }

    /**
     * Test attribute "user_roles"
     */
    public function testPropertyUserRoles()
    {
    }

    /**
     * Test attribute "write_token"
     */
    public function testPropertyWriteToken()
    {
    }
}
