<?php
/**
 * PlanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  sematext\stcloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace sematext\stcloud;

/**
 * PlanTest Class Doc Comment
 *
 * @category    Class
 * @description Plan
 * @package     sematext\stcloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlanTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Plan"
     */
    public function testPlan()
    {
    }

    /**
     * Test attribute "app_type"
     */
    public function testPropertyAppType()
    {
    }

    /**
     * Test attribute "custom"
     */
    public function testPropertyCustom()
    {
    }

    /**
     * Test attribute "data_retention_hours"
     */
    public function testPropertyDataRetentionHours()
    {
    }

    /**
     * Test attribute "default_trial_plan"
     */
    public function testPropertyDefaultTrialPlan()
    {
    }

    /**
     * Test attribute "free"
     */
    public function testPropertyFree()
    {
    }

    /**
     * Test attribute "free_trial_days"
     */
    public function testPropertyFreeTrialDays()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "max_alerts"
     */
    public function testPropertyMaxAlerts()
    {
    }

    /**
     * Test attribute "max_daily_events"
     */
    public function testPropertyMaxDailyEvents()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "plan_scheme"
     */
    public function testPropertyPlanScheme()
    {
    }

    /**
     * Test attribute "sematext_service"
     */
    public function testPropertySematextService()
    {
    }

    /**
     * Test attribute "trial_plan"
     */
    public function testPropertyTrialPlan()
    {
    }
}
