<?php
/**
 * AppsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Sematext\STCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Sematext\STCloud;

use Sematext\STCloud\Configuration;
use Sematext\STCloud\ApiException;
use Sematext\STCloud\ObjectSerializer;

/**
 * AppsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Sematext\STCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteUsingDELETE1
     *
     * delete.
     *
     */
    public function testDeleteUsingDELETE1()
    {
    }

    /**
     * Test case for getAppTypesUsingGET1
     *
     * Get all App types supported for the account identified with apiKey.
     *
     */
    public function testGetAppTypesUsingGET1()
    {
    }

    /**
     * Test case for getUsingGET1
     *
     * Gets defails for one particular App.
     *
     */
    public function testGetUsingGET1()
    {
    }

    /**
     * Test case for inviteAppGuestsUsingPOST1
     *
     * Invite guests to an app.
     *
     */
    public function testInviteAppGuestsUsingPOST1()
    {
    }

    /**
     * Test case for listAppsUsersUsingGET1
     *
     * Get all users of apps accessible to this account.
     *
     */
    public function testListAppsUsersUsingGET1()
    {
    }

    /**
     * Test case for listUsingGET
     *
     * Get all apps accessible by account identified with apiKey.
     *
     */
    public function testListUsingGET()
    {
    }

    /**
     * Test case for updateDescriptionUsingPUT1
     *
     * Update description of the app.
     *
     */
    public function testUpdateDescriptionUsingPUT1()
    {
    }

    /**
     * Test case for updateUsingPUT3
     *
     * Update app.
     *
     */
    public function testUpdateUsingPUT3()
    {
    }
}
