<?php
/**
 * SubscriptionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Sematext\STCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Sematext\STCloud;

use Sematext\STCloud\Configuration;
use Sematext\STCloud\ApiException;
use Sematext\STCloud\ObjectSerializer;

/**
 * SubscriptionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Sematext\STCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createForAppUsingPOST1
     *
     * Create App subscription.
     *
     */
    public function testCreateForAppUsingPOST1()
    {
    }

    /**
     * Test case for createForDashUsingPOST
     *
     * Create dashboard subscription.
     *
     */
    public function testCreateForDashUsingPOST()
    {
    }

    /**
     * Test case for deleteUsingDELETE2
     *
     * Delete subscription.
     *
     */
    public function testDeleteUsingDELETE2()
    {
    }

    /**
     * Test case for listUsingGET2
     *
     * Get subscriptions for an App.
     *
     */
    public function testListUsingGET2()
    {
    }

    /**
     * Test case for listUsingGET5
     *
     * Get current account's subscriptions.
     *
     */
    public function testListUsingGET5()
    {
    }

    /**
     * Test case for sendAppReportUsingPOST1
     *
     * Email an App report.
     *
     */
    public function testSendAppReportUsingPOST1()
    {
    }

    /**
     * Test case for sendDashReportUsingPOST
     *
     * Email a dashboard report.
     *
     */
    public function testSendDashReportUsingPOST()
    {
    }

    /**
     * Test case for toggleEnabledUsingPUT1
     *
     * Toggle subscription status.
     *
     */
    public function testToggleEnabledUsingPUT1()
    {
    }

    /**
     * Test case for updateForAppUsingPUT
     *
     * Update App subscription.
     *
     */
    public function testUpdateForAppUsingPUT()
    {
    }

    /**
     * Test case for updateForDashUsingPUT1
     *
     * Update dashboard subscription.
     *
     */
    public function testUpdateForDashUsingPUT1()
    {
    }
}
