<?php
/**
 * TokensApiControllerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  sematext\stcloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace sematext\stcloud;

use sematext\stcloud\Configuration;
use sematext\stcloud\ApiException;
use sematext\stcloud\ObjectSerializer;

/**
 * TokensApiControllerApiTest Class Doc Comment
 *
 * @category Class
 * @package  sematext\stcloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TokensApiControllerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAppToken1
     *
     * Create new app token.
     *
     */
    public function testCreateAppToken1()
    {
    }

    /**
     * Test case for deleteAppToken1
     *
     * Delete app token.
     *
     */
    public function testDeleteAppToken1()
    {
    }

    /**
     * Test case for getAppTokens1
     *
     * Get app available tokens.
     *
     */
    public function testGetAppTokens1()
    {
    }

    /**
     * Test case for regenerateAppToken
     *
     * Regenerate app token).
     *
     */
    public function testRegenerateAppToken()
    {
    }

    /**
     * Test case for updateAppToken1
     *
     * Update app token (enable/disable or name).
     *
     */
    public function testUpdateAppToken1()
    {
    }
}
